language: c
dist: trusty
sudo: required
before_install: echo starting nav_station\'s automated build and deployment pipeline
compiler: gcc

stages:
  - make
  - testing
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: make
      script:
        - echo entering make stage \(compile, identify branch, clean\)
        - make
        - ls src/
        - echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
        - make clean 
        - ls src/
