language: c
dist: trusty
before_install: cd src && echo $PWD
install: make
compiler: gcc
script:  make clean
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
