language: c
dist: trusty
sudo: required
before_install: echo starting nav_station\'s automated build and deployment pipeline
compiler: gcc

stages:
  - make

jobs:
  include:
    - stage: make
      script:
        - echo entering make stage \(compile, identify branch, clean\)
        - make -C src
        - ls src/
        - echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
        - make clean -C src
        - ls src/
