language: c
dist: trusty
sudo: required
before_install: cd src && echo $PWD
compiler: gcc

stages:
  - make

jobs:
  include:
    - stage: make
      script:
        - echo entering make stage \(compile, identify branch, clean\)
        - make
        - ls nav_station/*
        - echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
        - make clean
        - ls nav_station/*
